version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 1
      start_period: 1s
    volumes:
      - ./.ponder/db:/var/lib/postgresql/data
